#pragma once

#define CS_DISP_GPIO_Port GPIOA
#define SEL_DISP_Pin GPIO_PIN_4
#define SEL_DISP_GPIO_Port GPIOC
#define LED1_GPIO_Port GPIOC
#define FLAG0_Pin GPIO_PIN_1
#define FLAG0_GPIO_Port GPIOG
#define KT_Pin GPIO_PIN_15
#define KT_GPIO_Port GPIOE
#define A_A1_Pin GPIO_PIN_10
#define A_A1_GPIO_Port GPIOD
#define A_A2_Pin GPIO_PIN_11
#define A_A2_GPIO_Port GPIOD
#define A_A3_Pin GPIO_PIN_12
#define A_A3_GPIO_Port GPIOD
#define A_A4_Pin GPIO_PIN_13
#define A_A4_GPIO_Port GPIOD
#define A_LF1_Pin GPIO_PIN_2
#define A_LF1_GPIO_Port GPIOG
#define A_LF2_Pin GPIO_PIN_3
#define A_LF2_GPIO_Port GPIOG
#define A_A1S_Pin GPIO_PIN_4
#define A_A1S_GPIO_Port GPIOG
#define A_A0S_Pin GPIO_PIN_5
#define A_A0S_GPIO_Port GPIOG
#define A_LFS_Pin GPIO_PIN_6
#define A_LFS_GPIO_Port GPIOG
#define A_temp_Pin GPIO_PIN_7
#define A_temp_GPIO_Port GPIOG
#define SPI3_CS1_Pin GPIO_PIN_3
#define SPI3_CS1_GPIO_Port GPIOD
#define FMC_NE4_______________GPIO_Port GPIOG
#define SPI3_CS2_Pin GPIO_PIN_13
#define SPI3_CS2_GPIO_Port GPIOG
#define SPI3_CS3_Pin GPIO_PIN_14
#define SPI3_CS3_GPIO_Port GPIOG
#define KTG15_Pin GPIO_PIN_15
#define KTG15_GPIO_Port GPIOG
#define FL_DISP_Pin GPIO_PIN_6
#define FL_DISP_GPIO_Port GPIOB
